name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        include:
          - os: macos-latest
            install_deps:
              brew install llvm@9 pkg-config
            path_extension: $(brew --prefix llvm@9)/bin
          - os: ubuntu-18.04
            install_deps:
              wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
              sudo apt-get install libllvm12 llvm-12-dev pkg-config
              # sudo apt-get install llvm-9-tools llvm-9-dev pkg-config
            path_extension: /usr/lib/llvm-9/bin

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Haskell Stack
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-no-global: true
        stack-version: 'latest'

    - name: Install system dependencies
      run: |
        ${{ matrix.install_deps }}
        echo "${{ matrix.path_extension }}" >> $GITHUB_PATH

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          $GITHUB_WORKSPACE/.stack-work
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', 'stack*.yaml') }}
        restore-keys: ${{ runner.os }}-

    # This step is a workaround.
    # See issue for context: https://github.com/actions/cache/issues/445
    - name: Remove cached Setup executables
      run: rm -rf ~/.stack/setup-exe-cache
      if: runner.os == 'macOS'

    - name: Build
      run: cabal new-build all

    - name: Test
      run: cabal new-test all

    - name: Documentation
      run: cabal new-haddock all
